// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEdpf8VY61FGl_y4XSbJVOsnZGJ2__LEU',
    appId: '1:642256897038:web:55b9e73f76a09dd128685f',
    messagingSenderId: '642256897038',
    projectId: 'local-rental-app---flutter',
    authDomain: 'local-rental-app---flutter.firebaseapp.com',
    storageBucket: 'local-rental-app---flutter.firebasestorage.app',
    measurementId: 'G-FHLHBR7H9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzWwSwitR90pkpQpLfkl1OCq-vXJVcPLY',
    appId: '1:642256897038:android:8b1a4105f612c91f28685f',
    messagingSenderId: '642256897038',
    projectId: 'local-rental-app---flutter',
    storageBucket: 'local-rental-app---flutter.firebasestorage.app',
    databaseURL:
        'https://local-rental-app---flutter-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrP3AKJqoW_bfFB5ZEXGjN1MCB_Ngis-k',
    appId: '1:642256897038:ios:80c412a9b90e3e3128685f',
    messagingSenderId: '642256897038',
    projectId: 'local-rental-app---flutter',
    storageBucket: 'local-rental-app---flutter.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );
}
