name: Dart CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Dart
      # Note: Pin the Dart setup action to a tagged version for stability.
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          flutter: true  # Ensures the Flutter SDK is set up

      # Step 3: Install Android SDK dependencies (required for Flutter projects)

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get --verbose

      # Step 5: Analyze Dart code
      - name: Analyze project source
        run: dart analyze

      # Step 6: Run tests (use `flutter test` for Flutter projects)
      - name: Run tests
        run: flutter test
