name: Flutter CI Workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # Updated to latest stable version
          channel: stable
          cache: true  # Add caching for faster execution
          
      - name: Install dependencies
        run: |
          flutter pub cache repair  # Add cache repair step
          flutter pub get
          
      - name: Verify dependencies
        run: flutter pub outdated
        
      - name: Analyze project source
        run: flutter analyze --no-fatal-infos
        
      - name: Run tests
        run: flutter test
