name: Flutter CI Workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # Use the latest stable version
          channel: stable
          cache: true
          
      - name: Install Android SDK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lib32stdc++6 libglu1-mesa
          
      - name: Install dependencies
        run: |
          flutter pub get
          
      - name: Analyze project source
        run: flutter analyze
        
      - name: Run tests
        run: flutter test
