name: Flutter CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.6  # Replace with the latest stable version
          channel: stable          # Ensure the correct channel is used

      # Step 3: Install Android SDK dependencies
      - name: Install Android SDK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lib32stdc++6 libglu1-mesa

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get --verbose

      # Step 5: Analyze Dart code
      - name: Analyze project source
        run: flutter analyze

      # Step 6: Run tests
      - name: Run tests
        run: flutter test
