name: Build and Deploy Flutter App

on:
  push:
    branches:
      - master  # Change this from 'main' to 'master'
  pull_request:
    branches:
      - master  # Change this from 'main' to 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0' # Make sure this is the version you're using

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Firebase Deployment
      run: |
        firebase use --add
        firebase deploy --only hosting # Add hosting if you're deploying web too
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Set Firebase token in GitHub secrets
